### ISSUE TITLE
[Vue warn]: Error in nextTick: "RangeError: Maximum call stack size exceeded"

### ISSUE THREAD

**Issue by Monine** [probil/vue-moveable#27] opened 2019-08-29 12:34 UTC
e.g.
https://codesandbox.io/embed/vue-template-3wd0w

The key point is on the container property
Is my usage wrong?

**Comment by probil** [comment] 2019-08-29 13:03
Hi @Monine 👋 
Thanks for your issue. 

`container` param is optional. Are you sure you need it? 
I'll check your example more deeply soon. 

In a meantime you can check the code of the demo
https://github.com/probil/vue-moveable/blob/master/src/App.vue

**Comment by Monine** [comment] 2019-08-30 00:35
Yes, I want to be in a specific container.

**Comment by Monine** [comment] 2019-09-04 03:25
Is there any progress? We can discuss it together.

**Comment by probil** [comment] 2019-09-04 11:19
Hi @Monine 
I can confirm that there is a bug.
I don't have time right now to investigate the reason why it's happening.

It looks strange because there is nothing special about it. 🤔  
The component takes container element as a property and passes it to moveable. No magic here

Let's try to inline component from the repo to your codesandbox and use development version of vue so we have access to sourcemaps

**Comment by Monine** [comment] 2019-09-05 02:30
Think differently.
Is it possible to use custom directives to avoid this bug?
I will find time to try.

**Comment by romansp** [comment] 2019-10-16 16:13
After trying out different things I found out that `RangeError` is thrown when passed `container` prop is a `Vue` component itself. To avoid it you can create a wrapping element and pass it instead.

See updated codesandbox here: https://codesandbox.io/embed/vue-template-67q68

**Comment by romansp** [comment] 2019-10-17 10:56
Did further further investigation. This is happening due to watcher on `$props` being marked as `deep`. When passed `container` prop is a component then watcher has to traverse the whole object and eventually "traps" itself trying to build a dependency tree. 

Simple repro available here: https://codesandbox.io/s/vue-template-20djs. Try clicking `update` buttons and error will appear in the console. Removing `deep` fixes that. There is no dependency on `moveable` package whatsoever, so it's purely misuse of Vue's APIs.

To fix this should avoid deep-watching for changes on `container` prop.

**Comment by probil** [comment] 2019-10-17 13:38
This is cool.
Thanks for your time on investigation @romansp . Would you like to make a PR with a fix? 

Without `deep` on `$props` we can't handle reactive updates (to sync props and moveable). But I think we can watch props one-by-one so `deep` is not needed. There will be a lot of repetitions but I have an idea how to handle it.

**Comment by romansp** [comment] 2019-10-17 14:09
Yes, sure I will try and open a PR.

What do you think about changing component's API from enumerating all `moveable` options as separate props and use a single `options` prop instead? This `options` prop can be deep-watched separately. 

This might be a better option as component will support all existing (and future possible) `moveable` options by default, automatically fixing #31. Maybe it will be also possible to no longer pin `moveable` version in package.json and move to `dependencies`?

**Comment by probil** [comment] 2019-10-22 10:02
Released as part of v1.0.0

**Closed by probil** 2019-10-22 10:02 UTC
Labels: bug 🐛
